language: node_js
node_js:
  - 6
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $github_token  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage
