language: node_js
node_js:
  - 6
before_script:
  - npm install -g preact-cli
script: 
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $github_token  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master